const express=require('express');
const crypto=require('crypto');
const app=express();
app.use(express.json({limit:'1mb'}));
app.use(express.static('.'));
const PORT=process.env.PORT||10000;
const BIGBANG_API_KEY=process.env.BIGBANG_API_KEY||'';
const wallets=new Map(), applied=new Map();
function wallet(user){if(!wallets.has(user))wallets.set(user,{balance:1000,currency:'EUR'});return wallets.get(user);}
async function bb(path,options={}){if(!BIGBANG_API_KEY)throw new Error('BIGBANG_API_KEY is not configured');const r=await fetch('https://api.bigbangcasino.bet/api/v1'+path,{...options,headers:{'X-API-Key':BIGBANG_API_KEY,'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok||data.success===false){const e=new Error(data?.error?.message||('Provider HTTP '+r.status));e.status=r.status;e.data=data;throw e;}return data;}
app.get('/api/health',(req,res)=>res.json({ok:true,provider:'bigbang',configured:Boolean(BIGBANG_API_KEY),mode:BIGBANG_API_KEY.startsWith('ek_test_')?'sandbox':'unconfigured'}));
app.get('/api/games',async(req,res)=>{try{const q=new URLSearchParams({type:'standard',limit:String(Math.min(Number(req.query.limit)||100,100)),offset:'0'});if(req.query.search)q.set('search',String(req.query.search));res.json(await bb('/games?'+q));}catch(e){res.status(e.status||503).json({success:false,error:{message:e.message},setup:!BIGBANG_API_KEY});}});
app.post('/api/game-launch',async(req,res)=>{try{const gameId=Number(req.body.game_id),user=String(req.body.user_token||'np-test-user');if(!Number.isInteger(gameId))return res.status(400).json({success:false,error:{message:'game_id is required'}});const w=wallet(user);if(w.currency!=='EUR')return res.status(409).json({success:false,error:{message:'Configure the provider account for DKK before linking the DKK wallet.',code:'CURRENCY_NOT_CONFIGURED'}});await bb('/users/create',{method:'POST',body:JSON.stringify({user_token:user,username:user,country:'DK'})});res.json(await bb('/games/launch',{method:'POST',body:JSON.stringify({game_id:gameId,user_token:user,language:'da',return_url:req.body.return_url||'/casino.html'})}));}catch(e){res.status(e.status||503).json({success:false,error:{message:e.message,code:e.data?.error?.code||'LAUNCH_FAILED'}});}});
app.get('/wallet/user',(req,res)=>{const u=String(req.query.username||'');if(!u)return res.status(400).json({error:'username required'});const w=wallet(u);res.json({username:u,balance:w.balance.toFixed(2),currency:w.currency});});
app.post('/wallet/balance',(req,res)=>{const p=req.body||{};if(!BIGBANG_API_KEY)return res.status(503).json({error:'wallet provider not configured'});const base=String(p.username)+String(p.amount)+String(p.game)+String(p.game_category)+String(p.transaction_id),expected=crypto.createHmac('sha256',BIGBANG_API_KEY).update(base).digest('hex');if(!p.signature||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(String(p.signature))))return res.status(401).json({error:'bad signature'});const id=String(p.transaction_id);if(applied.has(id))return res.json({status:'ok',balance:applied.get(id).toFixed(2),duplicate:true});const w=wallet(String(p.username)),amount=Number(p.amount);if(!Number.isFinite(amount))return res.status(400).json({error:'invalid amount'});const next=Math.round((w.balance+amount)*100)/100;if(next<0)return res.status(400).json({error:'insufficient balance',balance:w.balance.toFixed(2)});w.balance=next;applied.set(id,next);res.json({status:'ok',balance:next.toFixed(2)});});
app.get('/api/wallet/:user',(req,res)=>{const w=wallet(String(req.params.user));res.json({user:req.params.user,balance:w.balance,currency:w.currency});});
app.listen(PORT,()=>console.log('NordicPlay casino test API listening on '+PORT));